"use client";
import React from "react";

/**
 * Disclaimer Page - US Paycheck Calculator
 * Optimized for SEO & AdSense readiness
 * Clean, readable layout with left alignment and professional tone.
 */

export default function Disclaimer(): React.ReactElement {
  const lastUpdated = "November 13, 2025";

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 via-gray-900 to-black text-white px-6 py-16">
      <div className="max-w-5xl mx-auto">
        <div className="p-8 rounded-2xl bg-gradient-to-tr from-gray-800/60 to-gray-900/60 backdrop-blur border border-gray-700">
          <h1 className="text-4xl font-bold mb-3">Disclaimer</h1>
          <p className="text-gray-400 mb-8 text-sm">Last updated: {lastUpdated}</p>

          {/* Main Content */}
          <section className="space-y-6 text-gray-300 leading-relaxed">
            <p>
              The information provided on <strong>USPaycheck.com</strong> is intended solely for
              general informational and educational purposes. While we strive to provide accurate
              and up-to-date data, all results generated by our paycheck calculator are estimates.
              You should not rely on these figures as professional tax, legal, or financial advice.
            </p>

            <h2 className="text-2xl font-semibold text-white">1. Not Professional Advice</h2>
            <p>
              This website and its calculator are not substitutes for professional services.
              Always seek guidance from a certified tax advisor, accountant, or payroll expert
              before making decisions about your taxes, salary, or withholdings.
            </p>

            <h2 className="text-2xl font-semibold text-white">2. Accuracy and Limitations</h2>
            <p>
              Although our data is based on the latest IRS tax tables and state withholding rules,
              we cannot guarantee full accuracy. Tax laws frequently change, and deductions may vary
              depending on individual circumstances and employer policies.
            </p>

            <h2 className="text-2xl font-semibold text-white">3. No Liability</h2>
            <p>
              USPaycheck.com and its team are not liable for any losses, errors, or damages
              resulting from reliance on the information or calculations provided. Use this tool
              at your own discretion.
            </p>

            <h2 className="text-2xl font-semibold text-white">4. User Responsibility</h2>
            <p>
              It is the user's responsibility to verify the accuracy of results before filing
              taxes or making payroll-related decisions. Always refer to the
              <a
                href="https://www.irs.gov"
                className="text-emerald-400 hover:underline ml-1"
                target="_blank"
                rel="noopener noreferrer"
              >
                official IRS website
              </a>{" "}
              and your state’s Department of Revenue for official tax information.
            </p>

            <h2 className="text-2xl font-semibold text-white">5. External Links</h2>
            <p>
              Our site may contain external links to government or financial resources. We are
              not responsible for the content, accuracy, or reliability of any external websites
              linked from USPaycheck.com.
            </p>

            <h2 className="text-2xl font-semibold text-white">6. Advertising and Affiliates</h2>
            <p>
              To support our operations, USPaycheck.com may display ads or affiliate links.
              However, we do not endorse any specific advertisers or guarantee product accuracy.
              Ads are served automatically through trusted third-party networks like Google AdSense.
            </p>

            <h2 className="text-2xl font-semibold text-white">7. Updates to This Disclaimer</h2>
            <p>
              This disclaimer may be revised periodically. We encourage users to review it
              frequently to stay informed about how we protect and communicate our legal
              responsibilities.
            </p>

            <h2 className="text-2xl font-semibold text-white">8. Contact Us</h2>
            <p>
              For questions about this Disclaimer or our site, please contact us at:
            </p>
            <p className="text-emerald-400 underline">support@uspaycheck.com</p>
          </section>

          {/* Footer Buttons */}
          <div className="mt-10 flex flex-wrap gap-4">
            <a
              href="/"
              className="px-5 py-2 rounded-lg bg-emerald-500 text-black font-semibold hover:bg-emerald-400 transition"
            >
              Open Calculator
            </a>
            <a
              href="/contact"
              className="px-5 py-2 rounded-lg border border-gray-600 hover:border-emerald-500 transition"
            >
              Contact
            </a>
          </div>

          {/* Footer */}
          <footer className="mt-8 text-xs text-gray-500">
            © {new Date().getFullYear()} USPaycheck.com. All rights reserved.
          </footer>
        </div>
      </div>
    </div>
  );
}
